# SPDX-FileCopyrightText: Copyright (c) 2024 Qorvo, Inc.
# SPDX-License-Identifier: LicenseRef-QORVO-2
#
# This file contains selected Kconfig options for the application.



CONFIG_DEBUG_THREAD_INFO=y
# CONFIG_DEBUG_OPTIMIZATIONS=y

CONFIG_NRFX_SPIM3=y
CONFIG_HSSPI=y
CONFIG_LOG=y
CONFIG_APP_LOG_LEVEL_DBG=y
CONFIG_INIT_STACKS=y

CONFIG_MAIN_STACK_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

CONFIG_THREAD_CUSTOM_DATA=y
CONFIG_POLL=y

CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000
CONFIG_HEAP_MEM_POOL_SIZE=16384
CONFIG_THREAD_NAME=y
CONFIG_THREAD_MAX_NAME_LEN=16
CONFIG_THREAD_STACK_INFO=y
CONFIG_THREAD_MONITOR=y
CONFIG_LOG_BUFFER_SIZE=4096
CONFIG_UCI_TRANSPORT_USE_QMUTILS=y
CONFIG_QOSAL_MAX_MUTEX=8
CONFIG_CHERRY_EXAMPLES_ZEPHYR=y
CONFIG_CHERRY_EXAMPLES_GETOPT_SUPPORT=y
CONFIG_PICOLIBC_IO_FLOAT=y
CONFIG_SHELL=y
CONFIG_SHELL_LOG_BACKEND=n
CONFIG_LOG_BACKEND_UART=y
CONFIG_SHELL_THREAD_PRIORITY_OVERRIDE=y
CONFIG_LOG_PROCESS_TRIGGER_THRESHOLD=1
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_LOG_BACKEND_RTT=n
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_USE_RUNTIME_CONFIGURE=y
CONFIG_CHERRY_BRIDGE_ZEPHYR=y
